name: cml
on: [push]
jobs:
  run:
    runs-on: [ubuntu-latest]
    container: docker://dvcorg/cml-py3:latest
    steps:
      - uses: actions/checkout@v2
      - name: cml_run
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cat metrics.txt >> report.md
          cml-publish history.png --md --title 'history' >> report.md
          cml-publish auc.png --md --title 'AUC' >> report.md
          cml-publish cm.png --md --title 'confusion-matrix' >> report.md
          cml-send-comment report.md 
